/*  Machine generated symbol file "esentprf.hxx" from "perfdata.txt" */


#define ESE 0
#define PagesConvertedSec 2
#define PagesConvertedTotal 4
#define RecordsConvertedSec 6
#define RecordsConvertedTotal 8
#define OLDTasksRunning 10
#define OLDTasksPending 12
#define OLDTasksDiscarded 14
#define OLDTasksPostedPerSec 16
#define OLDTasksCompletedPerSec 18
#define OSHeapAllocPerSec 20
#define OSHeapFreePerSec 22
#define OSHeapAlloc 24
#define OSHeapBytesAlloc 26
#define OSPageBytesReserved 28
#define OSPageBytesCommitted 30
#define FCBAsyncScan 32
#define FCBAsyncPurge 34
#define FCBAsyncThresholdScan 36
#define FCBAsyncThresholdPurge 38
#define FCBAsyncThresholdPurgeFailConflict 40
#define FCBAsyncThresholdPurgeFailInUse 42
#define FCBAsyncThresholdPurgeFailSentinel 44
#define FCBAsyncThresholdPurgeFailDeletePending 46
#define FCBAsyncThresholdPurgeFailOutstandingVersions 48
#define FCBAsyncThresholdPurgeFailLVOutstanding 50
#define FCBAsyncThresholdPurgeFailIndexOutstanding 52
#define FCBAsyncThresholdPurgeFailActiveTasks 54
#define FCBAsyncThresholdPurgeFailCallbacks 56
#define FCBAsyncThresholdPurgeFailOther 58
#define FCBAsyncPurgeFailConflict 60
#define FCBAsyncPurgeFailInUse 62
#define FCBAsyncPurgeFailSentinel 64
#define FCBAsyncPurgeFailDeletePending 66
#define FCBAsyncPurgeFailOutstandingVersions 68
#define FCBAsyncPurgeFailLVOutstanding 70
#define FCBAsyncPurgeFailIndexOutstanding 72
#define FCBAsyncPurgeFailActiveTasks 74
#define FCBAsyncPurgeFailCallbacks 76
#define FCBAsyncPurgeFailOther 78
#define FCBSyncPurge 80
#define FCBSyncPurgeStalls 82
#define FCBAllocWaitForVersionCleanup 84
#define FCBPurgeOnClose 86
#define FCBCacheHits 88
#define FCBCacheRequests 90
#define FCBCacheStalls 92
#define FCBCacheMax 94
#define FCBCachePreferred 96
#define FCBCacheAlloc 98
#define FCBCacheAllocRate 100
#define FCBCacheAllocAvail 102
#define FCBAttachedRCE 104
#define PIBInUse 106
#define PIBUsed 108
#define PIBTotal 110
#define ResMgrFCBAlloc 112
#define ResMgrFCBAllocUsed 114
#define ResMgrFCBQuota 116
#define ResMgrFUCBAlloc 118
#define ResMgrFUCBAllocUsed 120
#define ResMgrFUCBQuota 122
#define ResMgrTDBAlloc 124
#define ResMgrTDBAllocUsed 126
#define ResMgrTDBQuota 128
#define ResMgrIDBAlloc 130
#define ResMgrIDBAllocUsed 132
#define ResMgrIDBQuota 134
#define TableOpenCacheHitRate 136
#define TableOpenCacheRequests 138
#define TableOpenCacheHitsPerSec 140
#define TableOpenCacheMissesPerSec 142
#define TableOpenPagesReadPerSec 144
#define TableOpenPagesPreReadPerSec 146
#define TableOpensPerSec 148
#define TableClosesPerSec 150
#define TablesOpen 152
#define LGBytesWrittenPerSec 154
#define LGBytesGeneratedPerSec 156
#define LGBufferBytesUsed 158
#define LGBufferBytesFree 160
#define LGBufferBytesCommitted 162
#define LGUsersWaiting 164
#define LGCheckpointDepth 166
#define LGLogGenerationCheckpointDepth 168
#define CheckpointMaintOutstandingIOMax 170
#define UserROTrxCommit0PerSec 172
#define UserRWDurableTrxCommit0PerSec 174
#define UserRWLazyTrxCommit0PerSec 176
#define UserWaitAllTrxCommitPerSec 178
#define UserWaitLastTrxCommitPerSec 180
#define UserTrxCommit0PerSec 182
#define UserROTrxRollback0PerSec 184
#define UserRWTrxRollback0PerSec 186
#define UserTrxRollback0PerSec 188
#define SystemROTrxCommit0PerSec 190
#define SystemRWDurableTrxCommit0PerSec 192
#define SystemRWLazyTrxCommit0PerSec 194
#define SystemTrxCommit0PerSec 196
#define SystemROTrxRollback0PerSec 198
#define SystemRWTrxRollback0PerSec 200
#define SystemTrxRollback0PerSec 202
#define RecoveryStallReadOnly 204
#define RecoveryLongStallReadOnly 206
#define RecoveryStallReadOnlyTime 208
#define RecoveryThrottleIOSmoothing 210
#define RecoveryThrottleIOSmoothingTime 212
#define IODatabaseFileExtensionAsyncConsumed 214
#define IODatabaseFileExtensionStall 216
#define IODatabaseFileShrinkStall 218
#define LGRecordPerSec 220
#define LGCapacityFlushPerSec 222
#define LGCommitFlushPerSec 224
#define LGFlushSkippedPerSec 226
#define LGFlushBlockedPerSec 228
#define LGFlushPerSec 230
#define LGWritePerSec 232
#define LGFullSegmentWritePerSec 234
#define LGPartialSegmentWritePerSec 236
#define LGBytesWastedPerSec 238
#define LGStallPerSec 240
#define VERcbucketAllocated 242
#define VERcbucketDeleteAllocated 244
#define VERBucketAllocWaitForVersionCleanup 246
#define VERcbAverageBookmark 248
#define VERUnnecessaryCalls 250
#define VERAsyncCleanupTasksDispatched 252
#define VERSyncCleanupTasksDispatched 254
#define VERCleanupTasksDiscarded 256
#define VERCleanupTasksFailed 258
#define RECInserts 260
#define RECDeletes 262
#define RECReplaces 264
#define RECNoOpReplaces 266
#define RECRedundantReplaces 268
#define RECEscrowUpdates 270
#define RECIndexInserts 272
#define RECIndexDeletes 274
#define RECFalseIndexColumnUpdates 276
#define RECFalseTupleIndexColumnUpdates 278
#define RECUpdateIntrinsicLV 280
#define RECAddSeparateLV 282
#define RECAddForcedSeparateLV 284
#define RECForceSeparateAllLV 286
#define RECRefAllSeparateLV 288
#define RECDerefAllSeparateLV 290
#define LVSeeks 292
#define LVRetrieves 294
#define LVCreates 296
#define LVMaximumLID 298
#define LVUpdates 300
#define LVDeletes 302
#define LVCopies 304
#define LVChunkSeeks 306
#define LVChunkRetrieves 308
#define LVChunkAppends 310
#define LVChunkReplaces 312
#define LVChunkDeletes 314
#define LVChunkCopies 316
#define BTAppendSplit 318
#define BTRightSplit 320
#define BTRightHotpointSplit 322
#define BTVerticalSplit 324
#define BTSplit 326
#define BTEmptyPageMerge 328
#define BTRightMerge 330
#define BTPartialMerge 332
#define BTLeftMerge 334
#define BTPartialLeftMerge 336
#define BTPageMove 338
#define BTMerge 340
#define BTFailedSPCWriteLatch 342
#define BTSeekShortCircuit 344
#define BTOpportunePrereads 346
#define BTUnnecessarySiblingLatch 348
#define BTNext 350
#define BTNextNonVisibleNodesSkipped 352
#define BTNextNodesFiltered 354
#define BTPrev 356
#define BTPrevNonVisibleNodesSkipped 358
#define BTPrevNodesFiltered 360
#define BTSeek 362
#define BTInsert 364
#define BTReplace 366
#define BTFlagDelete 368
#define BTDelete 370
#define BTAppend 372
#define SPCreate 374
#define SPCreateCum 376
#define SPDelete 378
#define SPDeleteCum 380
#define SPPagesTrimmed 382
#define SPPagesTrimmedCum 384
#define SPPagesNotTrimmedUnaligned 386
#define SPPagesNotTrimmedUnalignedLogCum 388
#define SPPagesTrimmedDirty 390
#define SPPagesTrimmedDirtyCum 392
#define BFCacheMisses 394
#define BFCacheHits 396
#define BFCacheRequests 398
#define BFCacheUncorrelatedHitsPct 400
#define BFCacheRequests1 402
#define BFCacheRequestsPerSec 404
#define BFPctPinned 406
#define BFTotalBuffers1 408
#define BFPctClean 410
#define BFTotalBuffers2 412
#define BFPagesReadAsyncPerSec 414
#define BFPagesReadSyncPerSec 416
#define BFPagesDirtiedPerSec 418
#define BFPagesDirtiedRepeatedlyPerSec 420
#define BFPagesWrittenPerSec 422
#define BFOpportuneWriteIssued 424
#define BFPagesTransferredPerSec 426
#define BFOSPagesTrimmed 428
#define BFPagesTrimmed 430
#define BFPagesNonResidentReclaimedSuccess 432
#define BFPagesNonResidentReclaimedFailed 434
#define BFPagesNonResidentRedirectedToDatabase 436
#define BFPagesNonResidentEvicted 438
#define BFPagesOSFaultedInTotalTicks 440
#define BFPagesOSFaultedInTotalOperations 442
#define BFLatch 444
#define BFFastLatch 446
#define BFBadLatchHint 448
#define BFPctFastLatch 450
#define BFTotalLatches 452
#define BFTouchesNoTouch 454
#define BFTouches1Touches 456
#define BFTouches2Touches 458
#define BFTouchesCorrelatedTouches 460
#define BFSuperColdsUser 462
#define BFSuperColdsInternal 464
#define BFLatchConflict 466
#define BFLatchStall 468
#define BFPctAvail 470
#define BFTotalBuffers3 472
#define BFCacheFault 474
#define BFCacheEvict 476
#define BFCacheEvictUntouched 478
#define BFCacheEvictk1 480
#define BFCacheEvictk2 482
#define BFCacheEvictScavenge 484
#define BFCacheEvictScavengeSuperColdInternal 486
#define BFCacheEvictScavengeSuperColdUser 488
#define BFCacheEvictShrink 490
#define BFCacheEvictPurge 492
#define BFCacheEvictPatch 494
#define BFAvailStallsPerSec 496
#define BFCacheSizeMB 498
#define BFCacheSize 500
#define BFCacheSizeEffectiveMB 502
#define BFCacheSizeEffective 504
#define BFCacheMemoryCommittedMB 506
#define BFCacheMemoryCommitted 508
#define BFCacheMemoryReservedMB 510
#define BFCacheMemoryReserved 512
#define BFCacheSizeTargetMB 514
#define BFCacheSizeTarget 516
#define BFCacheSizeMin 518
#define BFCacheSizeMax 520
#define BFCacheSizeResident 522
#define BFCacheSizeResidentMB 524
#define BFCacheSizeUnattachedMB 526
#define BFCacheSizingDuration 528
#define BFPctStartFlushThreshold 530
#define BFTotalBuffers4 532
#define BFPctStopFlushThreshold 534
#define BFTotalBuffers5 536
#define BFPagesPreread 538
#define BFPagePrereadStalls 540
#define BFPagesPrereadUnnecessary 542
#define BFPagesDehydrated 544
#define BFPagesRehydrated 546
#define BFPagesVersioned 548
#define BFPagesVersionCopied 550
#define BFPctVersioned 552
#define BFTotalBuffers6 554
#define BFPagesRepeatedlyWritten 556
#define BFPagesFlushedCacheShrink 558
#define BFPagesFlushedCheckpoint 560
#define BFPagesFlushedCheckpointForeground 562
#define BFPagesFlushedContextFlush 564
#define BFPagesFlushedIdle 566
#define BFPagesFlushedFilthyForeground 568
#define BFPagesFlushedScavenge 570
#define BFPagesFlushedScavengeSuperColdInternal 572
#define BFPagesFlushedScavengeSuperColdUser 574
#define BFPagesFlushedOpportunely 576
#define BFPagesFlushedOpportunelyCleanPerSec 578
#define BFPagesCoalescedWritten 580
#define BFPagesCoalescedRead 582
#define BFSecondsLastScavengedResource 584
#define RESMGRCacheLifetimeSupercold 586
#define RESMGRCacheLifetimeLongest 588
#define RESMGRCacheLifetimeNormal 590
#define RESMGRCacheLifetimeLow 592
#define RESMGRCacheLifetimeAggVar 594
#define RESMGRCacheLifetimeK1 596
#define RESMGRCacheLifetimeK2 598
#define BFPageScanned 600
#define BFPageScannedMoves 602
#define BFPageScannedOutOfOrder 604
#define BFPageScannedTotal 606
#define RESMGRScanFoundEntries 608
#define RESMGRScanBucketsScanned 610
#define RESMGRScanEmptyBucketsScanned 612
#define RESMGRScanIdRange 614
#define RESMGRScanTimeRange 616
#define RESMGRScanFoundToEvictRange 618
#define RESMGRSuperColdedResources 620
#define RESMGRSuperColdAttempts 622
#define RESMGRSuperColdSuccesses 624
#define BFPageHistory 626
#define BFPageHistoryHits 628
#define BFPageHistoryReqs 630
#define BFPctResident 632
#define BFTotalBuffers7 634
#define BFPctDehydrated 636
#define BFTotalBuffers8 638
#define BFPagesRepeatedlyRead 640
#define BKReadIO 642
#define OLDPageReferenced 644
#define OLDPageRead 646
#define OLDPagePreread 648
#define OLDPageDirtied 650
#define OLDPageRedirtied 652
#define OLDPagesFreed 654
#define OLDPagesMerged 656
#define OLDPagesMoved 658
#define OLDLogRecord 660
#define OLDLogBytes 662
#define OLDLogRecordsTotal1 664
#define DBMaintDuration 666
#define DBMaintPagesRead 668
#define DBMaintPagesReadSec 670
#define DBMaintPagesZeroed 672
#define DBMaintPagesZeroedSec 674
#define DBMaintZeroRefCountLvsDeleted 676
#define DBMaintFDeletedLvPagesReclaimed 678
#define DBMaintBadChecksums 680
#define DBMaintIOReadsSec 682
#define DBMaintIOReadSize 684
#define DBMaintIOReadSizeIO 686
#define DBMaintThrottleSetting 688
#define DBMaintIOReReadsSec 690
#define DBMaintIOReReadSize 692
#define DBMaintIOReReadSizeIO 694
#define DBMaintIOReReadLatency 696
#define DBMaintIOReReadLatencyIO 698
#define DBTASKPageReferenced 700
#define DBTASKPageRead 702
#define DBTASKPagePreread 704
#define DBTASKPageDirtied 706
#define DBTASKPageRedirtied 708
#define DBTASKLogRecord 710
#define DBTASKLogBytes 712
#define DBTASKLogRecordsTotal1 714
#define OSFileDbReadIOAttached 716
#define OSFileDbReadIOTotalTicksAttached 718
#define OSFileDbReadIOTotal1Attached 720
#define OSFileDbReadIOTotalBytesAttached 722
#define OSFileDbReadIOTotal2Attached 724
#define OSFileDbReadIOInHeapAttached 726
#define OSFileDbReadIOAsyncPendingAttached 728
#define OSFileDbReadIOAbnormalLatencyAttached 730
#define OSFileDbReadIORecovery 732
#define OSFileDbReadIOTotalTicksRecovery 734
#define OSFileDbReadIOTotal1Recovery 736
#define OSFileDbReadIOTotalBytesRecovery 738
#define OSFileDbReadIOTotal2Recovery 740
#define OSFileDbReadIOInHeapRecovery 742
#define OSFileDbReadIOAsyncPendingRecovery 744
#define OSFileDbReadIOAbnormalLatencyRecovery 746
#define OSFileDbReadIOTotal 748
#define OSFileDbReadIOTotalTicksTotal 750
#define OSFileDbReadIOTotal1Total 752
#define OSFileDbReadIOTotalBytesTotal 754
#define OSFileDbReadIOTotal2Total 756
#define OSFileDbReadIOInHeapTotal 758
#define OSFileDbReadIOAsyncPendingTotal 760
#define OSFileDbReadIOAbnormalLatencyTotal 762
#define OSFileLogReadIO 764
#define OSFileLogReadIOTotalTicks 766
#define OSFileLogReadIOTotal1 768
#define OSFileLogReadIOTotalBytes 770
#define OSFileLogReadIOTotal2 772
#define OSFileLogReadIOInHeap 774
#define OSFileLogReadIOAsyncPending 776
#define OSFileLogReadIOAbnormalLatency 778
#define OSFileDbWriteIOAttached 780
#define OSFileDbWriteIOTotalTicksAttached 782
#define OSFileDbWriteIOTotal1Attached 784
#define OSFileDbWriteIOTotalBytesAttached 786
#define OSFileDbWriteIOTotal2Attached 788
#define OSFileDbWriteIOInHeapAttached 790
#define OSFileDbWriteIOAsyncPendingAttached 792
#define OSFileDbWriteIOAbnormalLatencyAttached 794
#define OSFileDbWriteIORecovery 796
#define OSFileDbWriteIOTotalTicksRecovery 798
#define OSFileDbWriteIOTotal1Recovery 800
#define OSFileDbWriteIOTotalBytesRecovery 802
#define OSFileDbWriteIOTotal2Recovery 804
#define OSFileDbWriteIOInHeapRecovery 806
#define OSFileDbWriteIOAsyncPendingRecovery 808
#define OSFileDbWriteIOAbnormalLatencyRecovery 810
#define OSFileDbWriteIOTotal 812
#define OSFileDbWriteIOTotalTicksTotal 814
#define OSFileDbWriteIOTotal1Total 816
#define OSFileDbWriteIOTotalBytesTotal 818
#define OSFileDbWriteIOTotal2Total 820
#define OSFileDbWriteIOInHeapTotal 822
#define OSFileDbWriteIOAsyncPendingTotal 824
#define OSFileDbWriteIOAbnormalLatencyTotal 826
#define OSFileLogWriteIO 828
#define OSFileLogWriteIOTotalTicks 830
#define OSFileLogWriteIOTotal1 832
#define OSFileLogWriteIOTotalBytes 834
#define OSFileLogWriteIOTotal2 836
#define OSFileLogWriteIOInHeap 838
#define OSFileLogWriteIOAsyncPending 840
#define OSFileLogWriteIOAbnormalLatency 842
#define OSSYNCThreadBlock 844
#define OSSYNCThreadsBlocked 846
#define FailedXpressCompressionBytesPerSec 848
#define CPAGEOtherReorganizeData 850
#define CPAGEFreeSpaceRequestReorganizeData 852
#define CPAGEPageMoveLoggingReorganizeData 854
#define CPAGEDehydrateBufferReorganizeData 856
#define ProgramMarker 858
#define BFCacheMissLatencyTotalTicksAttached 860
#define BFCacheMissTotalAttached 862
#define BFCacheSizeUnused 864
#define TableClass 866
#define TRECInserts 868
#define TRECDeletes 870
#define TRECReplaces 872
#define TRECNoOpReplaces 874
#define TRECRedundantReplaces 876
#define TRECEscrowUpdates 878
#define TRECIndexInserts 880
#define TRECIndexDeletes 882
#define TRECFalseIndexColumnUpdates 884
#define TRECFalseTupleIndexColumnUpdates 886
#define TRECUpdateIntrinsicLV 888
#define TRECAddSeparateLV 890
#define TRECAddForcedSeparateLV 892
#define TRECForceSeparateAllLV 894
#define TRECRefAllSeparateLV 896
#define TRECDerefAllSeparateLV 898
#define TLVSeeks 900
#define TLVRetrieves 902
#define TLVCreates 904
#define TLVMaximumLID 906
#define TLVUpdates 908
#define TLVDeletes 910
#define TLVCopies 912
#define TLVChunkSeeks 914
#define TLVChunkRetrieves 916
#define TLVChunkAppends 918
#define TLVChunkReplaces 920
#define TLVChunkDeletes 922
#define TLVChunkCopies 924
#define TBTAppendSplit 926
#define TBTRightSplit 928
#define TBTRightHotpointSplit 930
#define TBTVerticalSplit 932
#define TBTSplit 934
#define TBTEmptyPageMerge 936
#define TBTRightMerge 938
#define TBTPartialMerge 940
#define TBTLeftMerge 942
#define TBTPartialLeftMerge 944
#define TBTPageMove 946
#define TBTMerge 948
#define TBTFailedSPCWriteLatch 950
#define TBTSeekShortCircuit 952
#define TBTOpportunePrereads 954
#define TBTUnnecessarySiblingLatch 956
#define TBTNext 958
#define TBTNextNonVisibleNodesSkipped 960
#define TBTNextNodesFiltered 962
#define TBTPrev 964
#define TBTPrevNonVisibleNodesSkipped 966
#define TBTPrevNodesFiltered 968
#define TBTSeek 970
#define TBTInsert 972
#define TBTReplace 974
#define TBTFlagDelete 976
#define TBTDelete 978
#define TBTAppend 980
#define TSPCreate 982
#define TSPCreateCum 984
#define TSPDelete 986
#define TSPDeleteCum 988
#define TBFPagesPrereadUntouched 990
#define TBFCacheEvictk1 992
#define TBFCacheEvictk2 994
#define TBFCacheEvictScavenge 996
#define TBFCacheEvictShrink 998
#define TBFCacheEvictPurge 1000
#define TBFCacheEvictPatch 1002
#define TBFCacheSizeMB 1004
#define TBFCacheSize 1006
#define TBFCacheMisses 1008
#define TBFCacheHits 1010
#define TBFCacheRequests 1012
#define TBFCacheUncorrelatedHitsPct 1014
#define TBFCacheRequests1 1016
#define TBFCacheRequestsPerSec 1018
#define TBFPagesReadAsyncPerSec 1020
#define TBFPagesReadSyncPerSec 1022
#define TBFPagesDirtiedPerSec 1024
#define TBFPagesDirtiedRepeatedlyPerSec 1026
#define TBFPagesWrittenPerSec 1028
#define TBFPagesTransferredPerSec 1030
#define TBFPagesNonResidentReclaimedSuccess 1032
#define TBFPagesNonResidentReclaimedFailed 1034
#define TBFPagesNonResidentRedirectedToDatabase 1036
#define TBFPagesNonResidentEvicted 1038
#define TBFTouchesNoTouch 1040
#define TBFTouches1Touches 1042
#define TBFTouches2Touches 1044
#define TBFTouchesCorrelatedTouches 1046
#define TBFSuperColdsUser 1048
#define TBFSuperColdsInternal 1050
#define TBFPagesPreread 1052
#define TBFPagePrereadStalls 1054
#define TBFPagesPrereadUnnecessary 1056
#define TBFPagesDehydrated 1058
#define TBFPagesRehydrated 1060
#define TBFPagesVersioned 1062
#define TBFPagesVersionCopied 1064
#define TBFPagesRepeatedlyWritten 1066
#define TBFPagesFlushedCacheShrink 1068
#define TBFPagesFlushedCheckpoint 1070
#define TBFPagesFlushedCheckpointForeground 1072
#define TBFPagesFlushedContextFlush 1074
#define TBFPagesFlushedIdle 1076
#define TBFPagesFlushedFilthyForeground 1078
#define TBFPagesFlushedScavenge 1080
#define TBFPagesFlushedOpportunely 1082
#define TBFPagesFlushedOpportunelyCleanPerSec 1084
#define TBFPagesCoalescedWritten 1086
#define TBFPagesCoalescedRead 1088
#define TBFPagesRepeatedlyRead 1090
#define TFCBAsyncScan 1092
#define TFCBAsyncPurge 1094
#define TFCBAsyncThresholdScan 1096
#define TFCBAsyncThresholdPurge 1098
#define TFCBAsyncThresholdPurgeFailConflict 1100
#define TFCBAsyncThresholdPurgeFailInUse 1102
#define TFCBAsyncThresholdPurgeFailSentinel 1104
#define TFCBAsyncThresholdPurgeFailDeletePending 1106
#define TFCBAsyncThresholdPurgeFailOutstandingVersions 1108
#define TFCBAsyncThresholdPurgeFailLVOutstanding 1110
#define TFCBAsyncThresholdPurgeFailIndexOutstanding 1112
#define TFCBAsyncThresholdPurgeFailActiveTasks 1114
#define TFCBAsyncThresholdPurgeFailCallbacks 1116
#define TFCBAsyncThresholdPurgeFailOther 1118
#define TFCBAsyncPurgeFailConflict 1120
#define TFCBAsyncPurgeFailInUse 1122
#define TFCBAsyncPurgeFailSentinel 1124
#define TFCBAsyncPurgeFailDeletePending 1126
#define TFCBAsyncPurgeFailOutstandingVersions 1128
#define TFCBAsyncPurgeFailLVOutstanding 1130
#define TFCBAsyncPurgeFailIndexOutstanding 1132
#define TFCBAsyncPurgeFailActiveTasks 1134
#define TFCBAsyncPurgeFailCallbacks 1136
#define TFCBAsyncPurgeFailOther 1138
#define TFCBSyncPurge 1140
#define TTableOpenPagesReadPerSec 1142
#define TTableOpenPagesPreReadPerSec 1144
#define TBFCacheMissLatencyTotalTicksAttached 1146
#define TBFCacheMissTotalAttached 1148
#define TBFCacheSizeUnused 1150
#define Instances 1152
#define IPagesConvertedSec 1154
#define IPagesConvertedTotal 1156
#define IRecordsConvertedSec 1158
#define IRecordsConvertedTotal 1160
#define IOLDTasksRunning 1162
#define IOLDTasksPending 1164
#define IOLDTasksDiscarded 1166
#define IOLDTasksPostedPerSec 1168
#define IOLDTasksCompletedPerSec 1170
#define IFCBAsyncScan 1172
#define IFCBAsyncPurge 1174
#define IFCBAsyncThresholdScan 1176
#define IFCBAsyncThresholdPurge 1178
#define IFCBAsyncThresholdPurgeFailConflict 1180
#define IFCBAsyncThresholdPurgeFailInUse 1182
#define IFCBAsyncThresholdPurgeFailSentinel 1184
#define IFCBAsyncThresholdPurgeFailDeletePending 1186
#define IFCBAsyncThresholdPurgeFailOutstandingVersions 1188
#define IFCBAsyncThresholdPurgeFailLVOutstanding 1190
#define IFCBAsyncThresholdPurgeFailIndexOutstanding 1192
#define IFCBAsyncThresholdPurgeFailActiveTasks 1194
#define IFCBAsyncThresholdPurgeFailCallbacks 1196
#define IFCBAsyncThresholdPurgeFailOther 1198
#define IFCBAsyncPurgeFailConflict 1200
#define IFCBAsyncPurgeFailInUse 1202
#define IFCBAsyncPurgeFailSentinel 1204
#define IFCBAsyncPurgeFailDeletePending 1206
#define IFCBAsyncPurgeFailOutstandingVersions 1208
#define IFCBAsyncPurgeFailLVOutstanding 1210
#define IFCBAsyncPurgeFailIndexOutstanding 1212
#define IFCBAsyncPurgeFailActiveTasks 1214
#define IFCBAsyncPurgeFailCallbacks 1216
#define IFCBAsyncPurgeFailOther 1218
#define IFCBSyncPurge 1220
#define IFCBSyncPurgeStalls 1222
#define IFCBAllocWaitForVersionCleanup 1224
#define IFCBPurgeOnClose 1226
#define IFCBCacheHits 1228
#define IFCBCacheRequests 1230
#define IFCBCacheStalls 1232
#define IFCBCacheMax 1234
#define IFCBCachePreferred 1236
#define IFCBCacheAlloc 1238
#define IFCBCacheAllocRate 1240
#define IFCBCacheAllocAvail 1242
#define IFCBCacheAllocFailed 1244
#define IFCBCacheAllocLatency 1246
#define IFCBCacheAllocLatency1 1248
#define IFCBAttachedRCE 1250
#define IPIBInUse 1252
#define IPIBUsed 1254
#define IPIBTotal 1256
#define ITableOpenCacheHitRate 1258
#define ITableOpenCacheRequests 1260
#define ITableOpenCacheHitsPerSec 1262
#define ITableOpenCacheMissesPerSec 1264
#define ITableOpenPagesReadPerSec 1266
#define ITableOpenPagesPreReadPerSec 1268
#define ITableOpensPerSec 1270
#define ITableClosesPerSec 1272
#define ITablesOpen 1274
#define ILGBytesWrittenPerSec 1276
#define ILGBytesGeneratedPerSec 1278
#define ILGBufferSize 1280
#define ILGBufferBytesUsed 1282
#define ILGBufferBytesFree 1284
#define ILGBufferBytesCommitted 1286
#define ILGUsersWaiting 1288
#define ILGFileSize 1290
#define ILGCheckpointDepth 1292
#define ILGLogGenerationCheckpointDepth 1294
#define ICheckpointMaintOutstandingIOMax 1296
#define ILGLogGenerationCheckpointDepthTarget 1298
#define ILGLogCheckpointDepthAsAPctOfTarget 1300
#define ILGLogGenerationCheckpointDepthTarget2 1302
#define ILGLogGenerationCheckpointDepthMax 1304
#define ILGLogGenerationWaypointDepth 1306
#define ILGLogFileGenerated 1308
#define ILGLogFileGeneratedPrematurely 1310
#define ILGLogFileCurrentGeneration 1312
#define IUserROTrxCommit0PerSec 1314
#define IUserRWDurableTrxCommit0PerSec 1316
#define IUserRWLazyTrxCommit0PerSec 1318
#define IUserWaitAllTrxCommitPerSec 1320
#define IUserWaitLastTrxCommitPerSec 1322
#define IUserTrxCommit0PerSec 1324
#define IUserROTrxRollback0PerSec 1326
#define IUserRWTrxRollback0PerSec 1328
#define IUserTrxRollback0PerSec 1330
#define ISystemROTrxCommit0PerSec 1332
#define ISystemRWDurableTrxCommit0PerSec 1334
#define ISystemRWLazyTrxCommit0PerSec 1336
#define ISystemTrxCommit0PerSec 1338
#define ISystemROTrxRollback0PerSec 1340
#define ISystemRWTrxRollback0PerSec 1342
#define ISystemTrxRollback0PerSec 1344
#define IRecoveryStallReadOnly 1346
#define IRecoveryLongStallReadOnly 1348
#define IRecoveryStallReadOnlyTime 1350
#define IRecoveryThrottleIOSmoothing 1352
#define IRecoveryThrottleIOSmoothingTime 1354
#define IIODatabaseFileExtensionAsyncConsumed 1356
#define IIODatabaseFileExtensionStall 1358
#define IIODatabaseFileShrinkStall 1360
#define ILGRecordPerSec 1362
#define ILGCapacityFlushPerSec 1364
#define ILGCommitFlushPerSec 1366
#define ILGFlushSkippedPerSec 1368
#define ILGFlushBlockedPerSec 1370
#define ILGFlushPerSec 1372
#define ILGWritePerSec 1374
#define ILGFullSegmentWritePerSec 1376
#define ILGPartialSegmentWritePerSec 1378
#define ILGBytesWastedPerSec 1380
#define ILGStallPerSec 1382
#define IVERcbucketAllocated 1384
#define IVERcbucketDeleteAllocated 1386
#define IVERBucketAllocWaitForVersionCleanup 1388
#define IVERcbAverageBookmark 1390
#define IVERUnnecessaryCalls 1392
#define IVERAsyncCleanupDispatched 1394
#define IVERSyncCleanupDispatched 1396
#define IVERCleanupDiscarded 1398
#define IVERCleanupFailed 1400
#define IRECInserts 1402
#define IRECDeletes 1404
#define IRECReplaces 1406
#define IRECNoOpReplaces 1408
#define IRECRedundantReplaces 1410
#define IRECEscrowUpdates 1412
#define IRECIndexInserts 1414
#define IRECIndexDeletes 1416
#define IRECFalseIndexColumnUpdates 1418
#define IRECFalseTupleIndexColumnUpdates 1420
#define IRECUpdateIntrinsicLV 1422
#define IRECAddSeparateLV 1424
#define IRECAddForcedSeparateLV 1426
#define IRECForceSeparateAllLV 1428
#define IRECRefAllSeparateLV 1430
#define IRECDerefAllSeparateLV 1432
#define ILVSeeks 1434
#define ILVRetrieves 1436
#define ILVCreates 1438
#define ILVMaximumLID 1440
#define ILVUpdates 1442
#define ILVDeletes 1444
#define ILVCopies 1446
#define ILVChunkSeeks 1448
#define ILVChunkRetrieves 1450
#define ILVChunkAppends 1452
#define ILVChunkReplaces 1454
#define ILVChunkDeletes 1456
#define ILVChunkCopies 1458
#define IBTAppendSplit 1460
#define IBTRightSplit 1462
#define IBTRightHotpointSplit 1464
#define IBTVerticalSplit 1466
#define IBTSplit 1468
#define IBTEmptyPageMerge 1470
#define IBTRightMerge 1472
#define IBTPartialMerge 1474
#define IBTLeftMerge 1476
#define IBTPartialLeftMerge 1478
#define IBTPageMove 1480
#define IBTMerge 1482
#define IBTFailedSPCWriteLatch 1484
#define IBTSeekShortCircuit 1486
#define IBTOpportunePrereads 1488
#define IBTUnnecessarySiblingLatch 1490
#define IBTNext 1492
#define IBTNextNonVisibleNodesSkipped 1494
#define IBTNextNodesFiltered 1496
#define IBTPrev 1498
#define IBTPrevNonVisibleNodesSkipped 1500
#define IBTPrevNodesFiltered 1502
#define IBTSeek 1504
#define IBTInsert 1506
#define IBTReplace 1508
#define IBTFlagDelete 1510
#define IBTDelete 1512
#define IBTAppend 1514
#define ISPCreate 1516
#define ISPCreateCum 1518
#define ISPDelete 1520
#define ISPDeleteCum 1522
#define ISPPagesTrimmed 1524
#define ISPPagesTrimmedCum 1526
#define ISPPagesNotTrimmedUnaligned 1528
#define ISPPagesNotTrimmedUnalignedLogCum 1530
#define ISPPagesTrimmedDirty 1532
#define ISPPagesTrimmedDirtyCum 1534
#define IBFPagesPrereadUntouched 1536
#define IBFCacheEvictk1 1538
#define IBFCacheEvictk2 1540
#define IBFCacheEvictScavenge 1542
#define IBFCacheEvictShrink 1544
#define IBFCacheEvictPurge 1546
#define IBFCacheEvictPatch 1548
#define IBFCacheSizeMB 1550
#define IBFCacheMisses 1552
#define IBFCacheHits 1554
#define IBFCacheRequests 1556
#define IBFCacheUncorrelatedHitsPct 1558
#define IBFCacheRequests1 1560
#define IBFCacheRequestsPerSec 1562
#define IInstanceStatus 1564
#define IBFPagesReadAsyncPerSec 1566
#define IBFPagesReadSyncPerSec 1568
#define IBFPagesDirtiedPerSec 1570
#define IBFPagesDirtiedRepeatedlyPerSec 1572
#define IBFPagesWrittenPerSec 1574
#define IBFPagesTransferredPerSec 1576
#define IBFPagesNonResidentReclaimedSuccess 1578
#define IBFPagesNonResidentReclaimedFailed 1580
#define IBFPagesNonResidentRedirectedToDatabase 1582
#define IBFPagesNonResidentEvicted 1584
#define IBFTouchesNoTouch 1586
#define IBFTouches1Touches 1588
#define IBFTouches2Touches 1590
#define IBFTouchesCorrelatedTouches 1592
#define IBFSuperColdsUser 1594
#define IBFSuperColdsInternal 1596
#define IBFPagesPreread 1598
#define IBFPagePrereadStalls 1600
#define IBFPagesPrereadUnnecessary 1602
#define IBFPagesDehydrated 1604
#define IBFPagesRehydrated 1606
#define IBFPagesVersioned 1608
#define IBFPagesVersionCopied 1610
#define IBFPagesRepeatedlyWritten 1612
#define IBFPagesFlushedCacheShrink 1614
#define IBFPagesFlushedCheckpoint 1616
#define IBFPagesFlushedCheckpointForeground 1618
#define IBFPagesFlushedContextFlush 1620
#define IBFPagesFlushedIdle 1622
#define IBFPagesFlushedFilthyForeground 1624
#define IBFPagesFlushedScavenge 1626
#define IBFPagesFlushedOpportunely 1628
#define IBFPagesFlushedOpportunelyCleanPerSec 1630
#define IBFPagesCoalescedWritten 1632
#define IBFPagesCoalescedRead 1634
#define IBFPagesRepeatedlyRead 1636
#define IBKReadIO 1638
#define IOLDPageReferenced 1640
#define IOLDPageRead 1642
#define IOLDPagePreread 1644
#define IOLDPageDirtied 1646
#define IOLDPageRedirtied 1648
#define IOLDPagesFreed 1650
#define IOLDPagesMerged 1652
#define IOLDPagesMoved 1654
#define IOLDLogRecord 1656
#define IOLDLogBytes 1658
#define IOLDLogRecordsTotal1 1660
#define IDBMaintDuration 1662
#define IDBMaintPagesRead 1664
#define IDBMaintPagesReadSec 1666
#define IDBMaintPagesZeroed 1668
#define IDBMaintPagesZeroedSec 1670
#define IDBMaintZeroRefCountLvsDeleted 1672
#define IDBMaintFDeletedLvPagesReclaimed 1674
#define IDBMaintBadChecksums 1676
#define IDBMaintIOReadsSec 1678
#define IDBMaintIOReadSize 1680
#define IDBMaintIOReadSizeIO 1682
#define IDBMaintThrottleSetting 1684
#define IDBMaintIOReReadsSec 1686
#define IDBMaintIOReReadSize 1688
#define IDBMaintIOReReadSizeIO 1690
#define IDBMaintIOReReadLatency 1692
#define IDBMaintIOReReadLatencyIO 1694
#define IDBMaintFollowerSkips 1696
#define IDBMaintFollowerSkipsPerSec 1698
#define IDBMaintFollowerDivergentChecked 1700
#define IDBMaintFollowerDivergentCheckedSec 1702
#define IDBTASKPageReferenced 1704
#define IDBTASKPageRead 1706
#define IDBTASKPagePreread 1708
#define IDBTASKPageDirtied 1710
#define IDBTASKPageRedirtied 1712
#define IDBTASKLogRecord 1714
#define IDBTASKLogBytes 1716
#define IDBTASKLogRecordsTotal1 1718
#define IOSFileDbReadIOAttached 1720
#define IOSFileDbReadIOTotalTicksAttached 1722
#define IOSFileDbReadIOTotal1Attached 1724
#define IOSFileDbReadIOTotalBytesAttached 1726
#define IOSFileDbReadIOTotal2Attached 1728
#define IOSFileDbReadIOInHeapAttached 1730
#define IOSFileDbReadIOAsyncPendingAttached 1732
#define IOSFileDbReadIOAbnormalLatencyAttached 1734
#define IOSFileDbReadIORecovery 1736
#define IOSFileDbReadIOTotalTicksRecovery 1738
#define IOSFileDbReadIOTotal1Recovery 1740
#define IOSFileDbReadIOTotalBytesRecovery 1742
#define IOSFileDbReadIOTotal2Recovery 1744
#define IOSFileDbReadIOInHeapRecovery 1746
#define IOSFileDbReadIOAsyncPendingRecovery 1748
#define IOSFileDbReadIOAbnormalLatencyRecovery 1750
#define IOSFileDbReadIOTotal 1752
#define IOSFileDbReadIOTotalTicksTotal 1754
#define IOSFileDbReadIOTotal1Total 1756
#define IOSFileDbReadIOTotalBytesTotal 1758
#define IOSFileDbReadIOTotal2Total 1760
#define IOSFileDbReadIOInHeapTotal 1762
#define IOSFileDbReadIOAsyncPendingTotal 1764
#define IOSFileDbReadIOAbnormalLatencyTotal 1766
#define IOSFileLogReadIO 1768
#define IOSFileLogReadIOTotalTicks 1770
#define IOSFileLogReadIOTotal1 1772
#define IOSFileLogReadIOTotalBytes 1774
#define IOSFileLogReadIOTotal2 1776
#define IOSFileLogReadIOInHeap 1778
#define IOSFileLogReadIOAsyncPending 1780
#define IOSFileLogReadIOAbnormalLatency 1782
#define IOSFileDbWriteIOAttached 1784
#define IOSFileDbWriteIOTotalTicksAttached 1786
#define IOSFileDbWriteIOTotal1Attached 1788
#define IOSFileDbWriteIOTotalBytesAttached 1790
#define IOSFileDbWriteIOTotal2Attached 1792
#define IOSFileDbWriteIOInHeapAttached 1794
#define IOSFileDbWriteIOAsyncPendingAttached 1796
#define IOSFileDbWriteIOAbnormalLatencyAttached 1798
#define IOSFileDbWriteIORecovery 1800
#define IOSFileDbWriteIOTotalTicksRecovery 1802
#define IOSFileDbWriteIOTotal1Recovery 1804
#define IOSFileDbWriteIOTotalBytesRecovery 1806
#define IOSFileDbWriteIOTotal2Recovery 1808
#define IOSFileDbWriteIOInHeapRecovery 1810
#define IOSFileDbWriteIOAsyncPendingRecovery 1812
#define IOSFileDbWriteIOAbnormalLatencyRecovery 1814
#define IOSFileDbWriteIOTotal 1816
#define IOSFileDbWriteIOTotalTicksTotal 1818
#define IOSFileDbWriteIOTotal1Total 1820
#define IOSFileDbWriteIOTotalBytesTotal 1822
#define IOSFileDbWriteIOTotal2Total 1824
#define IOSFileDbWriteIOInHeapTotal 1826
#define IOSFileDbWriteIOAsyncPendingTotal 1828
#define IOSFileDbWriteIOAbnormalLatencyTotal 1830
#define IOSFileLogWriteIO 1832
#define IOSFileLogWriteIOTotalTicks 1834
#define IOSFileLogWriteIOTotal1 1836
#define IOSFileLogWriteIOTotalBytes 1838
#define IOSFileLogWriteIOTotal2 1840
#define IOSFileLogWriteIOInHeap 1842
#define IOSFileLogWriteIOAsyncPending 1844
#define IOSFileLogWriteIOAbnormalLatency 1846
#define IFailedXpressCompressionBytesPerSec 1848
#define ICPAGEOtherReorganizeData 1850
#define ICPAGEFreeSpaceRequestReorganizeData 1852
#define ICPAGEPageMoveLoggingReorganizeData 1854
#define ICPAGEDehydrateBufferReorganizeData 1856
#define IBFCacheMissLatencyTotalTicksAttached 1858
#define IBFCacheMissTotalAttached 1860
#define IBFCacheSizeUnused 1862
